Repository prooph/event-store-http-client, pull requests merged in 2019-01, with the labels that each got.

#10 implement VolatileEventStoreSubscription
  src/Internal/EventStoreHttpConnection.php
  src/Internal/VolatileEventStoreAllSubscription.php
  src/Internal/VolatileEventStoreStreamSubscription.php
Labels: enhancement

#11 implement catch up subscriptions
  src/ClientOperations/PersistentSubscriptionOperations.php
  src/ClientOperations/ReadFromSubscriptionOperation.php
  src/ConnectionSettings.php
  src/EventStoreConnectionFactory.php
  src/Exception/PersistentSubscriptionCommandFailedException.php
  src/Exception/ProjectionCommandConflictException.php
  src/Exception/ProjectionCommandFailedException.php
  src/Exception/UserCommandConflictException.php
  src/Exception/UserCommandFailedException.php
  src/Http/HttpClient.php
  src/Internal/EventStoreCatchUpSubscription.php
  src/Internal/EventStoreHttpAllCatchUpSubscription.php
  src/Internal/EventStoreHttpConnection.php
  src/Internal/EventStoreHttpStreamCatchUpSubscription.php
  src/Internal/VolatileEventStoreAllSubscription.php
  src/Internal/VolatileEventStoreStreamSubscription.php
  src/PersistentSubscriptions/PersistentSubscriptionsManager.php
  src/PersistentSubscriptions/PersistentSubscriptionsManagerFactory.php
  src/Projections/ProjectionsManager.php
  src/Projections/ProjectionsManagerFactory.php
  src/Projections/QueryManager.php
  src/Projections/QueryManagerFactory.php
  src/Uri.php
  src/UserManagement/UsersManager.php
  src/UserManagement/UsersManagerFactory.php
Labels: enhancement

#12 rename almost all exceptions
  src/ClientOperations/PersistentSubscriptionOperations.php
  src/ClientOperations/ReadFromSubscriptionOperation.php
  src/Exception/PersistentSubscriptionCommandFailed.php
  src/Exception/ProjectionCommandConflict.php
  src/Exception/ProjectionCommandFailed.php
  src/Exception/UserCommandConflictException.php
  src/Exception/UserCommandFailed.php
  src/Internal/EventStoreHttpConnection.php
  src/Internal/EventStoreHttpStreamCatchUpSubscription.php
  src/Internal/VolatileEventStoreAllSubscription.php
  src/Internal/VolatileEventStoreStreamSubscription.php
  src/PersistentSubscriptions/PersistentSubscriptionsManager.php
  src/Projections/ProjectionsManager.php
  src/UserManagement/UsersManager.php
Labels: enhancement

#17 implement Persistent Subscriptions
  src/ClientOperations/PersistentSubscriptionOperations.php
  src/ClientOperations/ReadFromSubscriptionOperation.php
  src/Internal/ConnectToPersistentSubscriptionOperation.php
  src/Internal/EventStoreHttpAllCatchUpSubscription.php
  src/Internal/EventStoreHttpConnection.php
  src/Internal/EventStoreHttpStreamCatchUpSubscription.php
  src/Internal/EventStorePersistentHttpSubscription.php
  src/Internal/PersistentEventStoreHttpSubscription.php
  src/Internal/ResolvedEventParser.php
Labels: bug, enhancement

#21 Tests
  src/ConnectionString.php
  src/Internal/EventStoreHttpConnection.php
  tests/Helper/StreamWriter.php
  tests/append_to_stream.php
  tests/appending_to_implicitly_created_stream.php
  tests/connection_factory_can.php
  tests/connection_string.php
Labels: enhancement

#22 Tests
  tests/deleting_stream.php
Labels: enhancement

#23 Tests
  src/Internal/EventStoreHttpAllCatchUpSubscription.php
  src/Internal/EventStoreHttpConnection.php
  tests/EventNumber.php
  tests/FakeEventStoreConnection.php
  tests/read_event_should.php
  tests/read_event_stream_backward_should.php
  tests/read_event_stream_forward_should.php
Labels: enhancement

#24 Tests
  src/Internal/EventStoreHttpConnection.php
  tests/read_stream_events_with_unresolved_linkto.php
  tests/soft_delete.php
  tests/when_working_with_metadata.php
  tests/when_working_with_raw_stream_metadata.php
  tests/when_working_with_stream_metadata_as_structured_info.php
Labels: enhancement

#25 Tests
  .travis.yml
  src/Internal/EventStoreHttpConnection.php
  tests/ProjectionSpecification.php
  tests/can_create_duplicate_persistent_subscription_group_name_on_different_streams.php
  tests/create_duplicate_persistent_subscription_group.php
  tests/create_persistent_subscription_after_deleting_the_same.php
  tests/create_persistent_subscription_group_without_permissions.php
  tests/create_persistent_subscription_on_all_stream.php
  tests/create_persistent_subscription_on_existing_stream.php
  tests/create_persistent_subscription_on_non_existing_stream.php
  tests/create_persistent_subscription_with_dont_timeout.php
  tests/create_persistent_subscription_with_too_big_checkpoint_after.php
  tests/create_persistent_subscription_with_too_big_message_timeout.php
  tests/deleting_existing_persistent_subscription_group_with_permissions.php
  tests/deleting_persistent_subscription_group_that_doesnt_exist.php
  tests/deleting_persistent_subscription_group_without_permissions.php
  tests/read_all_events_forward_with_hard_deleted_stream_should.php
  tests/read_all_events_forward_with_linkto_passed_max_count.php
  tests/read_all_events_forward_with_soft_deleted_stream_should.php
  tests/soft_delete.php
  tests/update_existing_persistent_subscription.php
  tests/update_existing_persistent_subscription_without_permissions.php
  tests/update_non_existing_persistent_subscription.php
  tests/when_creating_continuous_projection.php
  tests/when_creating_continuous_projection_with_track_emitted_streams.php
  tests/when_creating_one_time_projection.php
  tests/when_creating_transient_projection.php
  tests/when_disabling_projections.php
  tests/when_enabling_projections.php
  tests/when_resetting_projections.php
Labels: enhancement

#27 Fix lastEventNumber on failure
  src/Internal/EventStoreHttpConnection.php
Labels: bug

#26 Tests + fix meta write
  src/Internal/EventStoreHttpConnection.php
  tests/a_nak_in_subscription_handler_in_autoack_mode_drops_the_subscription.php
  tests/read_all_events_backward_should.php
  tests/read_all_events_backward_with_linkto_deleted_event.php
  tests/read_all_events_forward_should.php
  tests/read_all_events_forward_with_linkto_to_deleted_event.php
  tests/read_event_of_linkto_to_deleted_event.php
  tests/when_having_max_count_set_for_stream.php
  tests/when_having_truncatebefore_set_for_stream.php
  tests/when_listing_all_projections.php
  tests/when_listing_continuous_projections.php
  tests/when_listing_one_time_projections.php
Labels: bug, enhancement

#28 refactor factories
  src/EventStoreConnectionFactory.php
  src/Internal/EventStoreHttpConnection.php
  src/PersistentSubscriptions/PersistentSubscriptionsManager.php
  src/PersistentSubscriptions/PersistentSubscriptionsManagerFactory.php
  src/Projections/ProjectionsManager.php
  src/Projections/ProjectionsManagerFactory.php
  src/Projections/QueryManager.php
  src/Projections/QueryManagerFactory.php
  src/UserManagement/UsersManager.php
  src/UserManagement/UsersManagerFactory.php
  tests/Helper/TestConnection.php
  tests/PersistentSubscriptionManagement/persistent_subscription_manager.php
  tests/ProjectionSpecification.php
  tests/UserManagement/TestWithNode.php
  tests/UserManagement/list_users.php
  tests/connection_factory_can.php
Labels: enhancement
